# Generated by Django 2.2.6 on 2020-07-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20200712_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=50)),
            ],
        ),
    ]
