# Generated by Django 2.2.6 on 2020-07-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20200713_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='dui',
            new_name='dui_paciente',
        ),
    ]
