# Generated by Django 2.2.6 on 2020-07-14 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_cuadromedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadromedico',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.Paciente', unique=True),
        ),
    ]
