# Generated by Django 2.2.6 on 2020-07-14 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_auto_20200714_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadromedico',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.Paciente'),
        ),
    ]
