# Generated by Django 2.2.6 on 2020-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200711_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dui',
            field=models.CharField(default=324, max_length=15),
            preserve_default=False,
        ),
    ]
